name: fast_file_picker
description: "Fast file pickers for Flutter"
version: 1.0.0
homepage: https://github.com/flutter-cavalry/fast_file_picker

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

platforms:
  android:
  ios:
  macos:
  windows:
  linux:

dependencies:
  file_selector: ^1.0.1
  flutter:
    sdk: flutter
  ios_document_picker: ^0.4.0
  macos_file_picker: ^0.7.2
  path: ^1.9.0
  saf_util: ^3.1.0
  accessing_security_scoped_resource: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mgenware_dart_lints: ^8.0.0
